apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: allin1-playbook-signing-pipeline
spec:
  tasks:
  # 1. sign
  - name: sign
    taskRef:
      name: allin1-sign
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: allin1-sign
spec:
  steps:
  - name: sign
    image: ghcr.io/hirokuni-kitahara/playbook-signer:simple
    imagePullPolicy: Always
